[build]
  # Comando para construir el proyecto
  command = "npm run build -- --configuration=production"
  
  # Directorio donde se generan los archivos estáticos
  publish = "dist/zuko-frontend"

[build.environment]
  # Versión de Node.js para el build
  NODE_VERSION = "20"

# Redirecciones para SPA (Single Page Application)
# Todas las rutas que no sean archivos se redirigen a index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de seguridad opcionales
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache para archivos estáticos
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
